### ISSUE TITLE
Waduh error nih bwang

### ISSUE THREAD

**Issue by officialdittaz** [amiruldev20/mywajs#11]
[MywaJS] Clearing trash & cache sessions...
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (node:fs:186:3)
    at Object.readdir (node:fs:1354:14)
    at Timeout._onTimeout (file:///home/runner/Fearless-waweb/node_modules/mywajs/src/Client.js:184:46)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ERR_INVALID_CALLBACK'
} Promise {
  <rejected> TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
      at makeCallback (node:fs:186:3)
      at Object.readdir (node:fs:1354:14)
      at Timeout._onTimeout (file:///home/runner/Fearless-waweb/node_modules/mywajs/src/Client.js:184:46)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7) {
    code: 'ERR_INVALID_CALLBACK'
  }
}

**Comment by amiruldev20** [comment]
iya sabar. false dlu saja

**Comment by amiruldev20** [comment]
sudah fix silahkan update & ada perubahan pada send message, cek di docs atau src/client
